apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: kafka
  namespace: default
spec:
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: instance-configure
          spec:
            containers:
              - name: create-kafka-instance
                # update the image if you are using a custom name
                image: kafka-pipeline:test
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: promise-configure
          spec:
            containers:
              - name: init-kafka-promise
                # update the image if you are using a custom name
                image: kafka-promise-pipeline:test
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: kafka.promise.styxsoft.io
    spec:
      group: promise.styxsoft.io
      scope: Namespaced
      names:
        plural: kafka
        singular: kafka
        kind: kafka
      versions:
        - name: v1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    replicas:
                      type: number

