#!/usr/bin/env sh
set -x

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
export replicas="$(yq eval '.spec.replicas' /kratix/input/object.yaml)"


# Replace defaults with user provided values
cat /tmp/transfer/kafka-instance.yaml |  \
  yq eval '.spec.kafka.replicas = env(replicas)' | \
  yq eval '.metadata.name = env(name)' - \
  > /kratix/output/kafka-instance.yaml
cat /kratix/output/kafka-instance.yaml
